FROM ubuntu:22.04

# Install OpenSSH server
RUN apt update && \
    apt install -y openssh-server && \
    mkdir /var/run/sshd

# Set root password (change "root123" to your password)
RUN echo "root:root123" | chpasswd

# Allow root login & password authentication
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Expose SSH port
EXPOSE 22

# Start SSH service
CMD ["/usr/sbin/sshd", "-D"]
