# Use Python official image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirement file and install packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY app.py .

# Expose port
EXPOSE 5000

# Run the app
CMD ["python", "app.py"]
