pipeline{
  agent any
  stages{
    stage('build'){
      steps{
        sh '''
            echo "Lisiting WORKSPACE contents:"
            ls -l ${WORKSPACE}
            echo "Build stage is completed"
        '''
      }
    }

    stage('deploy'){
      steps{
        sh '''
            echo "Executing the script.sh ..............."
            bash ${WORKSPACE}/linux/script.sh
            echo "Deployment is successful"
        '''
      }
    }
  }
}
