pipeline{
  agent any
  stages{
    stage('stage1'){
      steps{
        sh 'echo "This is stage1"'
      }
    }

    stage('stage2'){
      steps{
        sh ' bash ${WORKSPACE}/file1.sh'
      }
    }
  }
}
