pipeline{
agent any
stages{
  stage('build'){
    steps{
      sh 'echo "Build from GitHub"'
    }
  }
   stage('test'){
    steps{
      sh 'echo " Build from GitHub running on  'hostname'"'
    }
   }
}
}

    
